"""Real-DWG parser tests — covers libredgw conversion, INSERT expansion,
extended classification, and the on-disk fixture DXFs.

The fixture DXFs (tp104_str.dxf, tp104_mech.dxf) are produced from the
real Autodesk DWG files via libredwg's ``dwg2dxf`` binary. They are not
regenerated by the test suite — they're checked in for reproducibility.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import pytest

from app.services import dwg_convert, parse
from app.services.parse import _parse_dxf, classify_dxf_entity


FIXTURE_DIR = Path(__file__).parent / "fixtures"


# --------------------------------------------------------------------------- #
# libredwg binary
# --------------------------------------------------------------------------- #


def test_libredwg_available():
    if not dwg_convert.libredwg_available():
        pytest.skip("libredwg dwg2dxf binary not on host — install it or set LIBREDWG_BIN")
    bin_path = dwg_convert.find_libredwg()
    assert bin_path is not None
    assert bin_path.is_file()
    assert bin_path.stat().st_size > 0


# --------------------------------------------------------------------------- #
# INSERT (block reference) expansion
# --------------------------------------------------------------------------- #


def test_insert_expansion_emits_primitives():
    """A BLOCK + INSERT in modelspace expands into world-coord LINE primitives."""
    dxf = (
        "0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n"
        "0\nSECTION\n2\nBLOCKS\n"
        "0\nBLOCK\n8\n0\n2\nMYBLOCK\n10\n0.0\n20\n0.0\n30\n0.0\n"
        "0\nLINE\n8\n0\n10\n0.0\n20\n0.0\n11\n100.0\n21\n100.0\n"
        "0\nENDBLK\n0\nENDSEC\n"
        "0\nSECTION\n2\nENTITIES\n"
        "0\nINSERT\n8\n0\n2\nMYBLOCK\n10\n500.0\n20\n500.0\n41\n1.0\n42\n1.0\n50\n0.0\n"
        "0\nENDSEC\n0\nEOF\n"
    )
    parsed = _parse_dxf(dxf.encode("utf-8"), "synthetic.dxf")
    assert parsed.ok
    # The expanded LINE should be the only entity, and it should be at
    # world coords (500, 500) → (600, 600) (insert pt + block primitive).
    line_ents = [e for e in parsed.entities if e.get("type") == "LINE"]
    assert len(line_ents) == 1
    sp = line_ents[0]["startPoint"]
    ep = line_ents[0]["endPoint"]
    assert 499.0 <= sp["x"] <= 501.0 and 499.0 <= sp["y"] <= 501.0
    assert 599.0 <= ep["x"] <= 601.0 and 599.0 <= ep["y"] <= 601.0
    # The expanded primitive should be tagged with its source block name so
    # the classifier can apply block-name rules.
    assert line_ents[0].get("blockName") == "MYBLOCK"


def test_insert_expansion_with_rotation():
    """A rotated INSERT applies the rotation to its primitives."""
    dxf = (
        "0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n"
        "0\nSECTION\n2\nBLOCKS\n"
        "0\nBLOCK\n8\n0\n2\nRB\n10\n0.0\n20\n0.0\n30\n0.0\n"
        "0\nLINE\n8\n0\n10\n100.0\n20\n0.0\n11\n200.0\n21\n0.0\n"
        "0\nENDBLK\n0\nENDSEC\n"
        "0\nSECTION\n2\nENTITIES\n"
        "0\nINSERT\n8\n0\n2\nRB\n10\n0.0\n20\n0.0\n41\n1.0\n42\n1.0\n50\n90.0\n"
        "0\nENDSEC\n0\nEOF\n"
    )
    parsed = _parse_dxf(dxf.encode("utf-8"), "rotated.dxf")
    line_ents = [e for e in parsed.entities if e.get("type") == "LINE"]
    assert len(line_ents) == 1
    sp = line_ents[0]["startPoint"]
    ep = line_ents[0]["endPoint"]
    # 90° rotation around base (0, 0) turns (100, 0) → (0, 100) and
    # (200, 0) → (0, 200).
    assert abs(sp["x"]) < 1.0 and abs(sp["y"] - 100.0) < 1.0
    assert abs(ep["x"]) < 1.0 and abs(ep["y"] - 200.0) < 1.0


def test_insert_with_unknown_block_passes_through():
    """An INSERT referencing an undefined block is kept as-is."""
    dxf = (
        "0\nSECTION\n2\nHEADER\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n"
        "0\nSECTION\n2\nBLOCKS\n0\nENDSEC\n"
        "0\nSECTION\n2\nENTITIES\n"
        "0\nINSERT\n8\n0\n2\nMISSING\n10\n0.0\n20\n0.0\n41\n1.0\n42\n1.0\n50\n0.0\n"
        "0\nENDSEC\n0\nEOF\n"
    )
    parsed = _parse_dxf(dxf.encode("utf-8"), "missing.dxf")
    # INSERT remains in the entity list with blockName set.
    inserts = [e for e in parsed.entities if e.get("type") == "INSERT"]
    assert len(inserts) == 1
    assert inserts[0].get("blockName") == "MISSING"


# --------------------------------------------------------------------------- #
# Extended classification table
# --------------------------------------------------------------------------- #


@pytest.mark.parametrize(
    "entity, expected_kind",
    [
        # MECH layer names observed in TP-104 MECH GA.dwg
        ({"type": "TEXT", "layer": "DIM"}, "text"),
        ({"type": "LWPOLYLINE", "layer": "Phantom"}, "phantom"),
        ({"type": "LWPOLYLINE", "layer": "PANTHOM"}, "phantom"),
        ({"type": "LINE", "layer": "HIDDEN"}, "hidden"),
        ({"type": "LINE", "layer": "HIDDDEN"}, "hidden"),
        ({"type": "LINE", "layer": "CEN"}, "centerline"),
        ({"type": "LINE", "layer": "CENTER"}, "centerline"),
        ({"type": "LINE", "layer": "MAIN OBJECT"}, "equipment"),
        ({"type": "LINE", "layer": "BOX"}, "annotation"),
        ({"type": "LINE", "layer": "AM_5"}, "annotation"),
        ({"type": "LINE", "layer": "TXT-50"}, "annotation"),
        ({"type": "LWPOLYLINE", "layer": "FUTURE TOWER"}, "line"),
        ({"type": "LWPOLYLINE", "layer": "Sheeting"}, "annotation"),
        ({"type": "LINE", "layer": "handrail"}, "annotation"),
        ({"type": "LINE", "layer": "Chute"}, "annotation"),
        ({"type": "LINE", "layer": "REV-C"}, "annotation"),
        # Block-name rules (Revit 3D export)
        ({"type": "LINE", "blockName": "Part-116860372-114953"}, "beam"),
        ({"type": "LINE", "blockName": "Part-99-12"}, "beam"),
        ({"type": "LINE", "blockName": "Bolt-12345"}, "brace"),
        ({"type": "LINE", "blockName": "Connection-9"}, "brace"),
        ({"type": "LINE", "blockName": "GridLine-A"}, "gridline"),
        ({"type": "LINE", "blockName": "GridLine-GridA"}, "gridline"),
        ({"type": "LINE", "blockName": "Unknown-42"}, "unknown"),
    ],
)
def test_classify_extended_rules(entity, expected_kind):
    assert classify_dxf_entity(entity) == expected_kind


# --------------------------------------------------------------------------- #
# Fixture-based parsing — real DWG → DXF → entities
# --------------------------------------------------------------------------- #


def test_dxf_fixture_mech_parses_with_layers():
    p = FIXTURE_DIR / "tp104_mech.dxf"
    if not p.exists():
        pytest.skip("tp104_mech.dxf fixture missing — run scripts/regen_fixtures.sh")
    parsed = parse.parse_file(p, p.name)
    assert parsed.ok
    assert parsed.entity_count == 622
    assert len(parsed.layers) == 31
    # MECH has the typo layers PANTHOM / HIDDDEN plus MAIN OBJECT.
    layer_names = {l["name"] for l in parsed.layers}
    assert any("PHANTOM" in n.upper() or "PANTHOM" in n.upper() for n in layer_names)
    assert any("MAIN OBJECT" in n.upper() for n in layer_names)
    # Should classify into many distinct kinds (text/line/equipment/phantom/...).
    kinds = Counter(classify_dxf_entity(e) for e in parsed.entities)
    assert kinds.get("text", 0) > 50  # lots of real text labels
    assert kinds.get("equipment", 0) > 0  # MAIN OBJECT → equipment
    assert kinds.get("phantom", 0) > 0  # PANTHOM layer → phantom


def test_dxf_fixture_str_parses_with_entities():
    p = FIXTURE_DIR / "tp104_str.dxf"
    if not p.exists():
        pytest.skip("tp104_str.dxf fixture missing — run scripts/regen_fixtures.sh")
    parsed = parse.parse_file(p, p.name)
    assert parsed.ok
    # Real STR file should have thousands of geometric primitives after
    # INSERT expansion. If entity_count is ~2,275, the BLOCKS section
    # wasn't preserved or INSERT expansion didn't run.
    assert parsed.entity_count == 17_326
    assert len(parsed.layers) == 7
    # Should classify into beam / brace / gridline via block-name rules.
    kinds = Counter(classify_dxf_entity(e) for e in parsed.entities)
    assert kinds.get("beam", 0) > 0
    assert kinds.get("brace", 0) > 0
    assert kinds.get("gridline", 0) > 0
    # No DICTIONARY/FIELD/XRECORD pollution (these are OBJECTS not ENTITIES).
    type_counts = Counter(e["type"] for e in parsed.entities)
    assert "DICTIONARY" not in type_counts
    assert "FIELD" not in type_counts
    assert "XRECORD" not in type_counts
